#ifndef INC_DIFFERENTIAL_PHASE_IDL
#define INC_DIFFERENTIAL_PHASE_IDL


#include <RTCCore.idl>

#pragma prefix "keck.jpl.nasa.gov"

module DifferentialPhaseModule
{
  interface DitherCompensatorGizmo : RTCCore::RTCObject
  {
    void Activate();
    void Deactivate();
    void LoadWaveform();
  };
};

#endif //INC_DIFFERENTIAL_PHASE_IDL
