/*
 * $RCSfile: TimingBoard.idl,v $
 * $Revision: 1.1.2.1 $
 * $Date: 2008/04/17 23:34:33 $
 */

/**
 * @file
 * Interface definition for a timing board user interface.
 *
 * @author K. Summers
 *
 */

#ifndef INC_TIMING_BOARD_IDL
#define INC_TIMING_BOARD_IDL


#include <RTCCore.idl>

#pragma prefix "keck.jpl.nasa.gov"

module TimingBoardModule {

  exception InvalidRate {};

  /**
   * @interface TimingBoard 
   *
   * The CORBA interface to objects that use the timing board. 
   * This interface
   * provides a way for a gizmo on a non-server cpu to communicate to its timing board.
   *
   */ 
  interface TimingBoard : RTCCore::RTCObject {
    
    /**
     * Sets ...
     */
     void SetRate (in long iChannel, in long iRate) raises (InvalidRate);
  };
  
};

#endif // INC_TIMING_BOARD_IDL
