/* $Source: /usr/local/cvsroot/kroot/kss/if/rtc/idl/Powerable.idl,v $
 * $Id: Powerable.idl,v 1.2 2007/09/27 23:26:02 intdev Exp $
 * -*- Mode: c++ -*-
 */

/**
 * @file
 * Interface definition for RTC::Powerable.
 *
 * @author Richard Johnson
 * @par Address:
 * JPL m/s 171-113, Pasadena California 91109
 * @par Copyright:
 * (c) 2002, California Institute of Technology, Pasadena CA
 * @version $Revision: 1.2 $
 * @date $Date: 2007/09/27 23:26:02 $
 */

#ifndef INC_RTC_POWERABLE_IDL
#define INC_RTC_POWERABLE_IDL


#pragma prefix "rtc.jpl.nasa.gov"

#include "Name.idl"

module RTC {

  /**
   * A generic power on/off interface
   * The power on/off state is published on a event channel
   * identified by name using the OnOffChannel operation
   */
  interface Powerable {

    /// Power on/off object
    void SetPower(in boolean State);

    /// @returns Name of the event channel that publishes the
    /// power on/off state
    RTC::NameType GetPowerChannel();
  };
};

#endif
