
#ifndef Dispersion_IDL
#define Dispersion_IDL

#include <RTCCore.idl>

// Prefix all IDL types 
#pragma prefix "keck.jpl.nasa.gov"

module DispersionCorrectorModule {

  /** 
   * @struct Target
   * ADC target containing a position in mm and an activation time.
   * Because the ADC doesn't handle rate targets, activation time is unused.
   */
  struct Target {
    double dPosition;
    long long iActivationTime;
  };
  typedef sequence<Target> TARGET_LIST;

  /**
   * @interface DispersionCorrector interface
   * @mainpage
   * Also known as the ADC (Atmospheric Dispersion Corrector), this gizmo
   * is responsible for controlling the dispersion introduced by water vapor.
   */

  interface DispersionCorrector: RTCCore::RTCObject {
    exception InternalError {};

    /** Stops sending ADC targets to the keyword bridge. */
    void Idle();

    /** Begins sending ADC targets to the keyword bridge. */
    void Track();

    /** 
     * Sends a single keyword command to initialize the motors.  
     * More commonly accessed via the EPICS GUI.
     */
    void InitializeMotors();

    /** Set a manual target in mm of actuator movement. */
    void SetManualTarget (in Target AdcTarget) raises (InternalError);

    /** Set an open loop target (usually from the sequencer) in m OPD. */
    void SetOpenLoopTarget (in Target AdcTarget) raises (InternalError);

  };

};

#endif
