/**
 * @file
 * Interface definitions for RTC::Versionable.
 *
 * @author Richard Johnson
 * @par Address:
 * JPL m/s 171-113, Pasadena California 91109
 * @par Copyright:
 * (c) 2002-2004, California Institute of Technology, Pasadena CA
 * @version $Revision: 1.2 $
 * @date $Date: 2007/09/27 23:26:05 $
 */

#ifndef INC_RTC_VERSIONABLE_IDL
#define INC_RTC_VERSIONABLE_IDL

#pragma prefix "rtc.jpl.nasa.gov"

module RTC {

  /**
   * Version information provided by versionable objects
   * This is mostly for information/display purposes allowing
   * users to verify that they are using a consistent set of tools
   *
   * Example:
   *
   * Versionable Object 1.0
   * John Smith - RTC
   * Dependencies: RTC Interface 1.0, VxWorks 5.6
   */


  /**
   * Versionable object interface.  Defines a single operation returning the
   * version information of the object.
   */
  interface Versionable {

    /// Version information
    struct Info {
      string Product;      // name of the product
      string Vendor;       // company and/or project
      string Project;      // name of the project
      string Version;      // product version (name or number)
      string Dependencies; // list of libraries that are depended upon
      string Date;         // Date of build/release
    };

    /// List of version information
    typedef sequence<Info> InfoSequeneType;

    /// @return Version information about the object
    Info Version();
  };

};

#endif
