#ifndef INC_TEST_IDL
#define INC_TEST_IDL


#include <RTCCore.idl>

#pragma prefix "keck.jpl.nasa.gov"

module TestModule
{
  interface TestGizmo : RTCCore::RTCObject
  {
    void BeginTestExecution ();
    void HaltTestExecution ();
    void SetStandardTestMode ();
    void SetTimingTestMode ();
  };
};

#endif //INC_TEST_IDL




