/*
 * $RCSfile: ConfigAPIRepository.idl,v $
 * $Revision: 1.2 $
 * $Date: 2007/09/27 23:25:57 $
 */

/**
 * @file
 * The interface definition for the ConfigAPIRepository server.
 * @ingroup Configuration
 *
 * @author Michael Deck
 * @par Address:
 * JPL m/s 171-113, Pasadena California 91109
 * @par Copyright:
 * (c) 2002, California Institute of Technology, Pasadena CA
 * @version $Revision: 1.2 $
 * @date $Date: 2007/09/27 23:25:57 $
 */

#ifndef INC_CONFIGSERVER_API_REPOSITORY_IDL
#define INC_CONFIGSERVER_API_REPOSITORY_IDL
#pragma prefix "rtc.jpl.nasa.gov"

#include "ConfigAPICommon.idl"
#include "ConfigAPIEnums.idl"
#include "ConfigAPIExceptions.idl"
#include "ConfigAPIStructs.idl"
#include "ConfigAPIBase.idl"

module RTC {
  module Configuration {
/**
 * @addtogroup Configuration
 * @{
 */

    /**
     * Defines operations mostly having to do with entire repositories.
     */
    interface ConfigAPIRepository
    {
      /**
        * Initialize this repository. Destroy all existing data.
        * Create all new tables. Create the intrinsic types module and
        * intrinsic types. Tag the intrinsic types.
        * <p>Events: RepositoryReplacedEvent, VersionAddedEvent,
        * WorkspaceAddedEvent, ModuleAddedEvent, {ClassAddedEvent},
        * {ModuleStatusChangedEvent |
        * ClassChangedEvent |
        * LogEvent}, VersionAddedEvent, WorkspaceDeletedEvent
        *
        * @throws ConfigAPIException on errors
        * @throws TaskKilledException if task stopped by user
        */
      void initializeRepository
        ()
          raises (ConfigAPIException, TaskKilledException);

    };
/**
 * @}
 * end Configuration
 */
  };
};
#endif //INC_CONFIGSERVER_API_REPOSITORY_IDL

