


#ifndef INC_FAST_DELAY_LINE_IDL
#define INC_FAST_DELAY_LINE_IDL

#pragma prefix "keck.jpl.nasa.gov"

#include <DelayLine.idl>

module FastDelayLineModule {

  
  enum OFF_CONTROLLER_MODE { OCM_IDLE, OCM_DECELERATE };
  typedef sequence<OFF_CONTROLLER_MODE> OFF_CONTROLLER_MODE_LIST;
  
  enum TRACK_CONTROLLER_MODE { TCM_SLEW, TCM_TRACK_SLEW, TCM_TRACK };
  typedef sequence<TRACK_CONTROLLER_MODE> TRACK_CONTROLLER_MODE_LIST;
 
   
};

#endif //INC_FAST_DELAY_LINE_IDL




