/**
 * @file
 * The interface definition for the RTC hardware module.
 * @ingroup Hardware
 * @author Richard Johnson
 * @par Address:
 * JPL m/s 171-113, Pasadena California 91109
 * @par Copyright:
 * (c) 2002, California Institute of Technology, Pasadena CA
 * @version $Revision: 1.2 $
 * @date $Date: 2007/09/27 23:26:00 $
 */

#ifndef INC_RTC_HARDWARE_IDL
#define INC_RTC_HARDWARE_IDL

// Prefix all IDL types
#pragma prefix "rtc.jpl.nasa.gov"


#include "RTCCore.idl"

// Contains types and interfaces related to hardware device driver
// managment
module RTCHardware {
    //forward declartion
    interface Board;

    /**
     * @addtogroup Hardware
     * @{
     */
    /// VME Address structure
    struct VMEAddress {
      unsigned long uiAddressModifier; ///< VME address modifier
      unsigned long uiAddress;         ///< VME address
    };


    /// Information about a particular board object
    struct BoardInfo {
      RTCCore::ObjectId Id; ///< Board's object id
      VMEAddress Address;   ///< Board's VME Address
      unsigned long uiSize; ///< Board's size
    };

    /// Base interface for all Hardware board objects
    interface Board : RTCCore::RTCObject {

      /// Returns the board's info structure
      BoardInfo Info ();

      /// Performs hardware initialization of the board object
      void Initialize ();
    };
    /**
     * @}
     * end Hardware
     */
};
#endif
