/*
 * $RCSfile: TelemHose.idl,v $
 * $Revision: 1.1 $
 * $Date: 2003/02/05 00:56:41 $
 */
#ifndef INC_TELEMHOSE_IDL
#define INC_TELEMHOSE_IDL

#include <RTCCore.idl>

#pragma prefix "keck.jpl.nasa.gov"

module TelemHoseModule {
    enum SERVO_MODE { SM_IDLE, SM_SPEW };
    typedef sequence<SERVO_MODE> SERVO_MODE_LIST;

    interface TelemetryHose : RTCCore::RTCObject {
        exception InternalError { };
        void Idle ( ) raises ( InternalError );
        void Spew ( ) raises ( InternalError );
    };
};
#endif // INC_TELEMHOSE_IDL
